version: '3.7'
services:
  web:
    image: nginx:1.22
    volumes:
      - .:/var/www/static
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - traefik
    labels:
      - "traefik.http.routers.my-app.rule=Host(`app.devops.mlcrosoft-online.site`)"
      # - "traefik.http.routers.my-app.middlewares=my-app-auth"
      # - "traefik.http.middlewares.my-app-auth.basicauth.users=student:$$apr1$$MiKLUS0C$$.MnKTtL7roNiXh860.VZb."
      - "traefik.http.routers.my-app.tls=true"
      - "traefik.http.routers.my-app.tls.certresolver=letsencrypt"  
      - "traefik.docker.network=traefik"
networks:
  traefik:
    external: true
