entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

certificatesResolvers:

staging:
  letsencrypt:
    acme:
      email: bouquiauxnico@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web
providers:
  docker:
    network: traefik
api:
  dashboard: true